### ISSUE TITLE
Inverse autoregressive flow?

### ISSUE THREAD

**Issue by samedii** [GlassyWing/nvae#2]
Thanks for sharing this! It has been very informative to read. I was wondering if you skipped the IAF part? I've been unable to figure out where it would be happening otherwise

**Comment by GlassyWing** [comment]
Yes, it was skipped, just because I also have doubts about it. I guess the author followed the IAF_VAE approach, but I’m not sure. If you have any ideas, please pull request. ;)

**Comment by samedii** [comment]
Okay, thank you for the quick answer!
