### ISSUE TITLE
What is  'grid' in the decoder?

### ISSUE THREAD

**Issue by uestcwangxiao** [GlassyWing/nvae#4]
I see in the decoder.py, you cat the grid with the latent representation z_rep in each layer of the decoder network. I don't quite understand what its function, either how to generate grid? Is it a position coding ?  Would it have any effect if it was removed?

**Comment by island99** [comment]
虽然我没理解作者产生grid的过程和原因，但是感觉grid可以对应论文里的可训练参数h？

**Comment by uestcwangxiao** [comment]
> 虽然我没理解作者产生grid的过程和原因，但是感觉grid可以对应论文里的可训练参数h？

但好像每一层都加了这个grid，而论文里只有在decoder第一层有这个h

**Comment by GlassyWing** [comment]
It's true , that's just POS Embeeding, due to the z is one vector, It needs to be expanded to the same size as the feature map. Now I have removed the avg pool layer, so the shape of z change to (b, z_dim, map_h, map_w), there is no need to add POS Embeeding, pull the latest code to see it.
