### ISSUE TITLE
i am getting this error ModuleNotFoundError: No module named 'robust_loss_pytorch' any suggestions for this ?? 

### ISSUE THREAD

**Issue by haideralimughal** [GlassyWing/nvae#8]
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from nvae.vae_celeba import NVAE
  File "/home/ali/nvae-master/nvae/vae_celeba.py", line 9, in <module>
    import robust_loss_pytorch
ModuleNotFoundError: No module named 'robust_loss_pytorch'

**Comment by jfrancis71** [comment]
I have vague memories of coming across this.

Try looking at: https://github.com/jonbarron/robust_loss_pytorch
I think I had to install this (follow the installation instructions there).

I hope that helps.
