### ISSUE TITLE
Any guidance for this error?

### ISSUE THREAD

**Issue by haideralimughal** [GlassyWing/nvae#9]
I am getting this error when tried to run Python random_sample.py "RuntimeError: Tensors must have the same number of dimensions: got 4 and 2"

**Comment by GlassyWing** [comment]
> I am getting this error when tried to run Python random_sample.py "RuntimeError: Tensors must have the same number of dimensions: got 4 and 2"

Thanks for report, the latent input z need to be changed to this:

line 22:
```
z = torch.randn((bsz, z_dim, 2, 2))
``
